---
title: "p8105_hw5_lz2951"
author: "lz2951"
date: "2023-11-14"
output: github_document
---

```{r}
library(tidyverse)
```

# Problem 1

```{r}
homicide = 
  read_csv(file = "./data/homicide-data.csv")
```

The homicide data contains `r nrow(homicide)` rows and `r ncol(homicide)` columns. The variable names are `r colnames(homicide)`. The disposition of a homicide could be one of `r unique(homicide$disposition)`.

```{r}
homicide_prop =
  homicide |>
  mutate(city_state = str_c(city, ",", state)) |>
  group_by(city_state, disposition) |>
  summarize(n_disposition = n()) |>
  pivot_wider(names_from = disposition, values_from = n_disposition) |>
  mutate(
    prop = list(
      tibble(
      total_number = sum(`Closed by arrest`, `Closed without arrest`, `Open/No arrest`, na.rm = TRUE), 
      unsolved_number = sum(`Closed without arrest`, `Open/No arrest`, na.rm = TRUE)
      )
    )
  )
```


```{r}
homicide_prop_balti =
  homicide_prop |>
  filter(city_state == "Baltimore,MD") |>
  pull(prop) |>
  _[[1]]

prop_test_balti =
  prop.test(homicide_prop_balti$unsolved_number, homicide_prop_balti$total_number) |>
  broom::tidy()

estimated_prop_balti = pull(prop_test_balti, estimate)
conf_low_balti = pull(prop_test_balti, conf.low)
conf_high_balti = pull(prop_test_balti, conf.high)

estimated_prop_balti
conf_low_balti
conf_high_balti
```


```{r}
prop_test_city = function(prop) {
  test_result = prop.test(prop$unsolved_number, prop$total_number) |>
    broom::tidy(test_result)
  tibble(
    estimate = test_result$estimate,
    conf.low = test_result$conf.low,
    conf.high = test_result$conf.high
  )
}

homicide_prop =
  homicide_prop |>
  mutate(test_result = map(prop, prop_test_city)) |>
  unnest(c(prop, test_result))
```

```{r}
homicide_prop |>
  ggplot(aes(x = reorder(city_state, estimate), y = estimate, color = city_state)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = .5))
```

# Problem 2

```{r}
file_names =
  list.files(path = "./data/data")

read_subject = function(file_name) {
  path = str_c("./data/data/", file_name)
  subject_data = read_csv(path)
  
  subject_data
}
```


```{r}
con_exp_df = 
  tibble(
  subject = file_names,
  result = map(file_names, read_subject)
  ) |>
  unnest(result) |>
  separate(subject, sep = "_", into = c("group", "subject")) |>
  mutate(subject = sub("\\.csv", "", subject)) |>
  select(subject, everything()) |>
  pivot_longer(cols = week_1 : week_8, names_to = "week", values_to = "value") |>
  mutate(week = sub("week_", "", week)) |>
  mutate(week = as.numeric(week))
```

```{r}
con_exp_df |>
  ggplot(aes(x = week, y = value, color = subject, linetype = group )) +
  geom_line()
```

# Problem 3

```{r}
get_t_test_result = function(mu, n = 30, sigma = 5, alpha = 0.05) {
  df = rnorm(n, mean = mu, sd = sigma)
  result = 
    t.test(df, mu = 0, conf.level = 1 - alpha) |>
    broom::tidy() |>
    select(estimate, p.value)
    
  result
}

sim_result_df = 
  expand_grid(
    mu = 0:6,
    iter = 1:5000
  ) |>
  mutate(estimate_df = map(mu, get_t_test_result)) |>
  unnest(estimate_df) |>
  mutate(null_rej = p.value <= 0.05)
```


```{r}
sim_result_df |>
  group_by(mu, null_rej) |>
  summarize(n_result = n()) |>
  group_by(mu, null_rej) |>
  filter(null_rej == TRUE) |>
  mutate(power = n_result/5000) |>
  ggplot(aes(x = mu, y = power)) +
  geom_line()
```


```{r}
sim_result_df |>
  group_by(mu) |>
  summarize(mean_estimate = mean(estimate)) |>
  ggplot(aes(x = mu, y = mean_estimate)) +
  geom_line()

sim_result_df |>
  filter(null_rej == TRUE) |>
  group_by(mu) |>
  summarize(mean_estimate = mean(estimate)) |>
  ggplot(aes(x = mu, y = mean_estimate)) +
  geom_line()
```


